# Generated by Django 3.1.5 on 2021-02-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210131_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parrent',
            new_name='parent',
        ),
    ]
